GET http://localhost:3000/home/all


###

POST http://localhost:3000/home/63b86c49e803d085cf723417/new
Content-Type: application/json

{
 "chat": "chatter123"
}
###
PATCH http://localhost:3000/home/login
Content-Type: application/json

{
    "username": "Admin",
    "password": "Passs"
}
###

DELETE http://localhost:3000/home/63b78b1580d49fef8e6e5792

###

GET http://localhost:3000/home/63b7417d9df8d722efefab42

###
POST http://localhost:3000/home/chats/XYZ/Beckett
###
PATCH http://localhost:3000/home/chats/TEST/Beckett
Content-Type: application/json

{"input": "2"}